#!/usr/bin/env ruby

require 'yaml'
require 'json'

data_read = File.read('config_in.yml')
y = YAML.load(data_read)
y['tm']['comment'] = "This file is autogenerated. Look at config_in.yml instead";
json_str = JSON.pretty_generate(y)
File.write('config.json', json_str)
puts json_str
